"""empty message

Revision ID: 3ceeda8f09a9
Revises: 0d5d60b32c0d
Create Date: 2020-03-08 16:19:38.457656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ceeda8f09a9'
down_revision = '0d5d60b32c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('_s_password', sa.String(length=256), nullable=True))
    op.drop_column('student', 's_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_password', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('student', '_s_password')
    # ### end Alembic commands ###
